raritySymbols:
  '5': üü®
  '4': üü®
  '3': üü™
  '2': üü¶
  '1': üü©
  '-1': üü•


defaultProbs: 
  '4': 2
  '3': 5
  '2': 10
cards:
-
  name: –ö–∞–∫–∞—à–∏ –•–∞—Ç–∞–∫–µ
  rarity: 4
  photo:
    lvl1: 
      - photo-195428368_457240639_02ded63742f30a9489
    lvl2:
      - photo-195428368_457240737_89d276750816e84e02
      
-
  name: –ù–∞—Ä—É—Ç–æ –£–∑—É–º–∞–∫–∏
  rarity: 4
  photo:
    lvl1: 
      - photo-195428368_457240637_1e7c62f810f2fa34fe
    lvl2:
      - photo-195428368_457240746_54590140694a9058cc
      - photo-195428368_457240744_e12cf2cf97abe02c93
      - photo-195428368_457240745_0474ee3873f9e4f2b0
-
  name: –û–±–∏—Ç–æ –£—á–∏—Ö–∞
  rarity: 4
  photo:
    lvl1: 
      - photo-195428368_457240638_4a51cbb78ef2bd96a1
    lvl2: 
      - photo-195428368_457240738_1c271401c4fc293a09
      
-
  name: –°–∞—Å–∫–µ –£—á–∏—Ö–∞
  rarity: 4
  photo:
    lvl1:
      - photo-195428368_457240641_3b78b01e6aa4119deb
    lvl2:
      - photo-195428368_457240743_d07dc005054e5511c1
      - photo-195428368_457240741_881c627d7d2f8e9f1d
      - photo-195428368_457240742_d0530acd1a9a4ce4b4
-
  name: –ú–∏–Ω–∞—Ç–æ –ù–∞–º–∏–∫–∞–∑–µ
  rarity: 4
  photo:
    lvl1:
      - photo-195428368_457240640_a64ec1b5861beb0ae3
    lvl2: 
      - photo-195428368_457240740_18286024abd6e55e57
-
  name: –û—Ä–æ—á–∏–º–∞—Ä—É
  rarity: 4
  photo:
    lvl1: 
      - photo-195428368_457240642_9cb802c4daa95789ea
    lvl2: 
      - photo-195428368_457240739_21546ae5af5794606d
-
  name: –ú–∞–¥–∞—Ä–∞ –£—á–∏—Ö–∞
  rarity: -1
  photo:
    lvl1: 
      - photo-195428368_457240655_6883a6f20ec3ac41db
    lvl2: 
      - photo-195428368_457240722_ebfdd32618aab1020d
      - photo-195428368_457240724_89512d476eb3428391
      - photo-195428368_457240721_546ed8dfdce548b9c8
      - photo-195428368_457240723_5a1ab380b8b332504c
-
  name: –ê–Ω–∫–æ
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240718_e85a4092efc9467723
    lvl2: 
      - photo-195428368_457240783_c11beefcd2d66e28b0
-
  name: –ì–µ–Ω–º–∞
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240710_1095a3782e3733d643
    lvl2: 
      - photo-195428368_457240782_3831f1b4ccbbeedf5f
-
  name: –ì–æ–∑—É
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240719_1cc1249a8dfd53f80e
    lvl2: 
      - photo-195428368_457240780_22845086e3e53e07a4
-
  name: –î–∂–∏—Ä–æ–±–æ
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240715_74b01442025bab6f57
    lvl2: 
      - photo-195428368_457240777_9202a84ddd1ec8bc26
-
  name: –î–æ—Å—É
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240717_584a672e0c6443630c
    lvl2: 
      - photo-195428368_457240781_300b644a06c2c40be5
-
  name: –ó–∞–∫—É
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240716_e73e6c47d648433198
    lvl2: 
      - photo-195428368_457240776_d8cac41165d7ee2300
-
  name: –ö–∞–º–∏–∑—É–∫–∏
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240700_fdfe869b76b590522e
    lvl2: 
      - photo-195428368_457240778_3dc47d2c8e81ac4eda
-
  name: –ö–∏–±–∞ –ò–Ω—É–∑—É–∫–∞
  pool: 1
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240706_43c42f3c40ce05c0ac
    lvl2: 
      - photo-195428368_457240766_842e43fdd44a21eaac
-
  name: –ö–∏–¥–æ–º–∞—Ä—É
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240708_e0dfb14c99548a64fd
    lvl2: 
      - photo-195428368_457240775_e5d7b7fb7dc69aea75
-
  name: –ö–∏–Ω
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240707_c9e38e40feb967ba05
    lvl2: 
      - photo-195428368_457240773_1a19a4200dfb5cb156
-
  name: –ö–æ—Ç–µ—Ç—Å—É
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240714_87f20950c4e394a13a
    lvl2: 
      - photo-195428368_457240774_519176917acc346d0d
-
  name: –ú–µ–π–∑—É
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240713_4504c9898ef4cb1595
    lvl2: 
      - photo-195428368_457240779_ce2f675c50cbbac281
-
  name: –ú–∏–∑—É–∫–∏
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240709_538d75d1c73cce70bf
    lvl2: 
      - photo-195428368_457240772_41244b1245580c3942
-
  name: –ú–æ—ç–≥–∏
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240712_55edb07714c09bd324
    lvl2: 
      - photo-195428368_457240771_80a796a95cc29641e6
-
  name: –û–º–æ–∏
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240711_f4739e4fcaa1801012
    lvl2: 
      - photo-195428368_457240767_f3d893b6853b49a7b8
-
  name: –°–∞–º—É–∏
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240699_0d7b23e39bc6ca5c59
    lvl2: 
      - photo-195428368_457240768_c0b9f5bf8fe648cc02
-
  name: –°—É–∑—É–º–µ–±–∞—á–∏
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240702_e525a789ecd6d64e86
    lvl2: 
      - photo-195428368_457240769_7d8a5732ca68730038
-
  name: –¢–∞—é—è
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240704_fd578e137bfb0a8cfe
    lvl2: 
      - photo-195428368_457240763_c9c87eb06c26812b5e
-
  name: –¢–µ–º–∞—Ä–∏
  rarity: 1
  photo:
    lvl1:
      - photo-195428368_457240705_de59af9379709d75f1
    lvl2: 
      - photo-195428368_457240770_ca74231686eb51881e
-
  name: –¢–µ–Ω –¢–µ–Ω
  pool: 1
  rarity: 1
  photo:
    lvl1:
      - photo-195428368_457240695_12951c750ac611ba21
    lvl2:
      - photo-195428368_457240760_e5e9cf70e019204752
-
  name: –£–¥–æ–Ω
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240698_988befe61e8efca641
    lvl2: 
      - photo-195428368_457240758_eeaa167cfdc1044224
-
  name: –ß–æ–¥–∂–∏ –ê–∫–∏–º–∏—á–∏
  pool: 3
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240703_495cacde22143fe91e
    lvl2: 
      - photo-195428368_457240762_f5e845d548f163c9d9
-
  name: –ß–æ–∑–∞ –ê–∫–∏–º–∏—á–∏
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240701_f19ea18dc2acde1c14
    lvl2: 
      - photo-195428368_457240756_e310f5b8656bd2b4e7
-
  name: –®–∏–∑—É–Ω–µ
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240720_bd789e058f1801b570
    lvl2: 
      - photo-195428368_457240754_595e48f88bd13b741b
-
  name: –®–∏–Ω–æ –ê–±—É—Ä–∞–º–µ
  pool: 3
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240691_1785e0a466109f23d8
    lvl2: 
      - photo-195428368_457240765_39c534c828ff19acde
-
  name: –ö–∏—à–∏–º–∞—Ä—É
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240684_a7432457419991be0a
    lvl2: 
      - photo-195428368_457240749_e54ed966ef375ddd91
-
  name: –ö—É—à–∏–Ω–∞ –£–∑—É–º–∞–∫–∏
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240685_acc58252fbc0be114e
    lvl2: 
      - photo-195428368_457240747_4ee6786a01302c73dd
-
  name: –ú–∞–±—É–∏
  rarity: 1
  photo:
    lvl1:
      - photo-195428368_457240686_2b199e340962f3dbe8
    lvl2: 
      - photo-195428368_457240755_91b0faa3bf925575ae
-
  name: –ò–±–∏–∫–∏
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240687_ebc0233bd36f01a7fd
    lvl2: 
      - photo-195428368_457240753_aefe1c29ec102170a8
-
  name: –ß–∏—ë
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240688_630be0f317dfe4d893
    lvl2: 
      - photo-195428368_457240764_a04d5bcdae540275fe
-
  name: –§—É –Ø–º–∞–Ω–∞–∫–∞
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240689_91b3092c6aed7a1c8f
    lvl2: 
      - photo-195428368_457240748_26bacdc345bcb5c1bf
-
  name: –ú–∞–π—Ç–æ –î–∞–π
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240690_4ce44b1dde53400f8d
    lvl2: 
      - photo-195428368_457240751_0213af73bdc82e7899
-
  name: –¢–æ—Ä—É–Ω–µ –ê–±—É—Ä–∞–º–µ
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240692_fdbeb11bd47aa4b1f5
    lvl2: 
      - photo-195428368_457240759_6038d93b14dd363130
-
  name: –†–∞–π–≥–∞
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240693_ce2774ab7e3770ee92
    lvl2: 
      - photo-195428368_457240750_af436ccdc6c378f2ce
-
  name: –°–∞–π –ê–∫–∞—à–∏
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240694_b193a27f9eb377beaa
    lvl2: 
      - photo-195428368_457240752_c09a6349367ac7aae0
-
  name: –†–∏–Ω–≥–æ
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240696_67a97ef3d9105fae49
    lvl2: 
      - photo-195428368_457240757_52c019b654c6586c2b
-
  name: –ì—É—Ä–µ–Ω
  rarity: 1
  photo:
    lvl1: 
      - photo-195428368_457240697_c142265511ef9c64a3
    lvl2: 
      - photo-195428368_457240761_3e7bf92d4ebeeb6b3d
-
  name: –ê–æ
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240682_d7271754f8c319f50b
    lvl2: 
      - photo-195428368_457240811_149ab3ff97e766258c
-
  name: –ê—Å—É–º–∞ –°–∞—Ä—É—Ç–æ–±–∏
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240656_ba41976dcf883f5878
    lvl2: 
      - photo-195428368_457240798_070e197b3c42bbc243
-
  name: –î–∂—É–≥–æ
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240679_131f500abe3db705d5
    lvl2: 
      - photo-195428368_457240806_4ac8e07921c4156aa1
-
  name: –î–∂—É–∑–æ –ë–∏–≤–∞
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240681_0e7a37974d40f4453e
    lvl2: 
      - photo-195428368_457240805_f1be97c7706fac3ab5

-
  name: –ò–Ω–æ –Ø–º–∞–Ω–∞–∫–∞
  pool: 2
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240677_e1542240a53c5c5697
    lvl2: 
      - photo-195428368_457240810_327351ea55ddcb05be
-
  name: –ò–Ω–æ–∏—á–∏ –Ø–º–∞–Ω–∞–∫–∞
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240678_748c5e738f50ecda4f
    lvl2: 
      - photo-195428368_457240801_d6f5695a39bb72cd61
-
  name: –ò—Ä—É–∫–∞ –£–º–∏–Ω–æ
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240676_7913e2257b70747b4a
    lvl2: 
      - photo-195428368_457240809_a224548991c69512fd
-
  name: –ö–∞–Ω–∫—É—Ä–æ
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240674_ecdd17dba9d0ae5321
    lvl2: 
      - photo-195428368_457240803_893ba6a552c7d09f31
-
  name: –Æ—Ö–∏ –ö—É—Ä–µ–Ω–∞–π
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240680_da68615c816acdd327
    lvl2: 
      - photo-195428368_457240799_afb4fb08329dab4622
-
  name: –ú–∏—Ñ—É–Ω–µ
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240675_97cf5a0c0f75d2ee70
    lvl2: 
      - photo-195428368_457240808_317132006330fe22f5
-
  name: –†–æ–∫ –õ–∏
  pool: 2
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240671_09d5c9598ec0230ab7
    lvl2: 
      - photo-195428368_457240795_8475bfc37ae1892d9c
-
  name: –†—å—é–∑–µ—Ç—Å—É
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240670_04b0609235ae4a4962
    lvl2: 
      - photo-195428368_457240794_74b1bb5a668ffd107c
-
  name: –°—É–π–≥–µ—Ü—É –•–æ–∑—É–∫–∏
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240673_55837a24b492251b74
    lvl2: 
      - photo-195428368_457240800_24c7b2c4be474689ed
-
  name: –•–∞–Ω–∑–æ –°–∞–ª–∞–º–∞–Ω–¥—Ä–∞
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240667_91803d8fdefc1e9dfd
    lvl2: 
      - photo-195428368_457240797_80fbb9d7dfefb02f28
-
  name: –•–∏–Ω–∞—Ç–∞ –•—å—é–≥–∞
  pool: 1
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240668_345bcd434e447b525a
    lvl2: 
      - photo-195428368_457240807_2cf498a88e71dc3177
-
  name: –®–∏–±–∏ –ê–±—É—Ä–∞–º–µ
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240663_9a397f5aa6f8de2d3a
    lvl2: 
      - photo-195428368_457240804_7198482a4fec63f833
-
  name: –®–∏–∫–∞–º–∞—Ä—É –ù–∞—Ä–∞
  pool: 2
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240672_187340bf066028cb1b
    lvl2: 
      - photo-195428368_457240796_af1313ceb87daaa82f
-
  name: –ö–∞—Ä–∏–Ω –£–∑—É–º–∞–∫–∏
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240683_06286ae5fe4a3f2919
    lvl2: 
      - photo-195428368_457240802_5c49b63ca3f8c92640
-
  name: –ö–æ–Ω–∞–Ω
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240657_1feac18b96bae7fef6
    lvl2: 
      - photo-195428368_457240786_e324e006d81dd2bd0d
-
  name: –ó–∞–±—É–∑–∞ –ú–æ–º–æ—á–∏
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240658_571b248c2e8f3562a9
    lvl2: 
      - photo-195428368_457240790_be2f90a809a61b51e2
-
  name: –ú–∞–π—Ç–æ –ì–∞–π
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240659_759c4140bc307c93fa
    lvl2: 
      - photo-195428368_457240788_1245b4db350759b084
-
  name: –î–µ–π–¥–∞—Ä–∞
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240660_dd353f1708259211f0
    lvl2: 
      - photo-195428368_457240823_0fbb489a3613cc6715
-
  name: –Ø—Ö–∏–∫–æ
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240661_b95915e9d3c8795517
    lvl2: 
      - photo-195428368_457240784_a04a2ba0d1f5e04df6
-
  name: –ì–∏–Ω–∫–∞–∫—É
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240662_51d5129e0d3e96d10e
    lvl2: 
      - photo-195428368_457240793_8854cb9f75c4d2534f
-
  name: –°–∞—Å–æ—Ä–∏
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240664_e03140de7c59ff6f80
    lvl2: 
      - photo-195428368_457240785_b314bbbebdaa571a04
-
  name: –î–∞—Ä—É–∏
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240665_d6d40ff33c8161074f
    lvl2: 
      - photo-195428368_457240791_19d0a0b5ee46f7d3d0
-
  name: –ö–∏–Ω–∫–∞–∫—É
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240666_b754cf22a5f30bec24
    lvl2: 
      - photo-195428368_457240792_fa0a9dbaac273df116
-
  name: –ö–∞–±—É—Ç–æ
  rarity: 2
  photo:
    lvl1: 
      - photo-195428368_457240669_074cbe720a2e2d18b2
    lvl2: 
      - photo-195428368_457240787_01083d75189be8e404
-
  name: –ì–∞–∞—Ä–∞
  rarity: 3
  photo:
    lvl1: 
      - photo-195428368_457240650_bc55807741f84769ec
    lvl2: 
      - photo-195428368_457240734_d9b35e1d7a73f97430
-
  name: –î–∂–∏—Ä–∞–π–∞
  rarity: 3
  photo:
    lvl1: 
      - photo-195428368_457240645_1cc3b640a1001b381c
    lvl2: 
      - photo-195428368_457240735_beacac4d252b0396cb
-
  name: –ù–µ–π–¥–∂–∏ –•—å—é–≥–∞
  rarity: 3
  photo:
    lvl1: 
      - photo-195428368_457240643_af0fe1d0bcc1cdabaf
    lvl2: 
      - photo-195428368_457240736_25d3409708fb628603
-
  name: –°–∞–∫–æ–Ω
  rarity: 3
  photo:
    lvl1: 
      - photo-195428368_457240654_5b3dd1704d0a1c173b
    lvl2: 
      - photo-195428368_457240730_bdfb03fd5bf8477ec3
-
  name: –°–∞–∫—É—Ä–∞ –•–∞—Ä—É–Ω–æ
  pool: 3
  rarity: 3
  photo:
    lvl1: 
      - photo-195428368_457240648_a4c3041f60665e93fa
    lvl2: 
      - photo-195428368_457240733_2bdc202e5e9398ff09
-
  name: –Ø–º–∞—Ç–æ
  rarity: 3
  photo:
    lvl1: 
      - photo-195428368_457240646_890335f7c7326bb01e
    lvl2: 
      - photo-195428368_457240732_ee80e8aa3fff4d2b3f
-
  name: –î–∞–Ω–∑–æ –®–∏–º—É—Ä–∞
  rarity: 3
  photo:
    lvl1: 
      - photo-195428368_457240647_4668d92e4ea1e0d3ae
    lvl2: 
      - photo-195428368_457240725_c3ebcf7f7be9be3396
-
  name: –¢–æ–±–∏—Ä–∞–º–∞ –°–µ–Ω–¥–∂—É
  rarity: 3
  photo:
    lvl1: 
      - photo-195428368_457240644_54f6b753ed5544a8da
    lvl2: 
      - photo-195428368_457240726_00385a87f6966957a3
-
  name: –®–∏—Å—É–∏ –£—á–∏—Ö–∞
  rarity: 3
  photo:
    lvl1: 
      - photo-195428368_457240649_fb5662a0326cafbe9a
    lvl2: 
      - photo-195428368_457240728_b7118f3bc17610a496
-
  name: –ö–∏–º–∏–º–∞—Ä–æ –ö–∞–≥—É—è
  rarity: 3
  photo:
    lvl1: 
      - photo-195428368_457240652_ff667beee4d00bff6b
    lvl2: 
      - photo-195428368_457240729_f1593478d0f7fcfa56
-
  name: –•–∞–∫—É
  rarity: 3
  photo:
    lvl1: 
      - photo-195428368_457240653_745510aa1001df6efd
    lvl2: 
      - photo-195428368_457240731_42474c8883fca62420
-
  name: –ö–∞–∫—É–∑—É
  rarity: 3
  photo:
    lvl1: 
      - photo-195428368_457240651_f34d182c3da388c49b
    lvl2: 
      - photo-195428368_457240727_cafdfa6f7fe4fb8853
-
  name: –õ–µ—Ö–∞ –õ–µ–ø–µ—Ö–∞
  rarity: 5
  photo:
    lvl1: 
      - photo-195428368_457240812_67429750609ea35cd5
-
  name: –†–∏–∫
  rarity: 5
  photo:
    lvl1: 
      - photo-195428368_457240813_804a25daf77054d14f
-
  name: –Ø—Å—É–æ
  rarity: 5
  photo:
    lvl1: 
      - photo-195428368_457240814_58bea3fb59929953b4
-
  name: EXAMPLE_CARD
  rarity: -32767
  photo:
    lvl1:
      - photo-195428368_457242498_b0371aca2d0d3c9e6c
